project:
  type: website
  output-dir: ../qscribe-docs

website:
  title: "QuBiTAi"
  site-url: https://qubitai.in/
  description: "A Quarto-based documentation site for QuBiTAi" 
  favicon: images/AudioWide-White.ico
  navbar:
    right:
      - text: Home
        href: ../index.html
      - text: QFey
        href: https://qfey.in/
        target: _blank
      - text: QuBiTAi
        href: https://qubitai.in/
        target: _blank
      - text: About
        href: https://qubitai.in/about.html
        target: _blank
      - icon: github
        href: https://github.com/rvbug
        target: _blank


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

